title: Bassik IDRISSOUM
logo: /jpg/profil.jpg
description: "Portfolio Chargé d'études Statistiques / Data Analyst / Modélisation et Évaluation"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
